JGIspring.application.name=guideTouristique
spring.data.mongodb.database=guideTouristique_db
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
saad.app.jwtSecret=NyZXRLZXkyMDI1SGlkZGVuU3BvdHNTZWNyZXRL8741FPNLFUND73BS57NF02KSudz985fd
saad.app.jwtExpirationMs= 86400000
geoapify.api.key=37f3b34b9a5645be803c6038d8428e36